### ISSUE TITLE
Get liquid variables used in text

### ISSUE THREAD

**Issue by hardiksondagar** [jg-rp/liquid#54]
- Ability to get liquid variables used in the given text. 
- This is useful when dynamic context creation is required, database queries can be optimized to get only the required data/context.

Example
```
1.
text - Hello {{customer_name}}
variables - [customer_name]
this requires database query to get customer_name

2.
text - Hello there
variables - []
this doesn't require database interaction as no variables are used.
```

I have attempted to do something like this, but it doesn't work with conditions and pipes.
```
text = "Hello {{customer_name}}"
variables = []
liquid_obj = liquid_env.from_string(text)
for node in liquid_obj.tree.statements:
    try:
        for item in node.expression.expression.path:
            variables.append(item.value)
    except:
        pass
```

**Comment by jg-rp** [comment]
Hi @hardiksondagar,

Since Python Liquid version 1.2.0, you can use [`BoundTemplate.analyze()`](https://jg-rp.github.io/liquid/api/BoundTemplate#analyze) to get a template's variables.

Docs: https://jg-rp.github.io/liquid/guides/static-template-analysis
Source: https://github.com/jg-rp/liquid/blob/main/liquid/template.py#L367

For example:

```python
from liquid import Environment

env = Environment()
text = "Hello {{ customer_name }}"
template = env.from_string(text)

analysis = template.analyze()
variables = list(analysis.variables)
print(variables)
```
**Output**
```text
['customer_name']
```

The [`TemplateAnalysis`](https://jg-rp.github.io/liquid/api/template-analysis) object returned from `analyze()` includes variables found in all tag expressions, not just output statements.

```python
from liquid import Environment

env = Environment()

text = """
{% for customer in all_customers %}
  Hello {{ customer.name | prepend: customer.title }}
{% endfor %}
"""

template = env.from_string(text)
analysis = template.analyze()

print("All variables: ", list(analysis.variables))
print("Global variables", list(analysis.global_variables))
``` 

**Output**
```text
All variables:  ['all_customers', 'customer.name', 'customer.title']
Global variables ['all_customers']
```

**Comment by hardiksondagar** [comment]
@jg-rp Thanks 👏🏽
