### ISSUE TITLE
Render shopify theme

### ISSUE THREAD

**Issue by gustavu92** [jg-rp/liquid#82]
Hello, I'm trying to render the Shopify Dawn theme, however on my first attempt I got this error:
`LiquidSyntaxError: unexpected tag 'style', on line 41`
These are the steps taken:
```
f = open("./dawn/layout/theme.liquid", "r")
theme_liquid = f.read()
template = Template(theme_liquid)
```
Would this be the correct step to render such a theme? Thanks a lot for the excellent work.

**Comment by jg-rp** [comment]
Hi @gustavu92,

In this case, Python Liquid has failed to parse the template because it does not recognise the `style` tag. `style` is a Shopify store extension to "standard" Liquid, so is not included in either Python Liquid or [Ruby Liquid](https://github.com/Shopify/liquid).

You'll find many tags and filters in the [Shopify store developer docs](https://shopify.dev/api/liquid/tags) that do not exist in the open source ["core" Liquid docs](https://shopify.github.io/liquid/), also from Shopify. It is possible to extend Python Liquid with [custom tags](https://jg-rp.github.io/liquid/guides/custom-tags) and [filters](https://jg-rp.github.io/liquid/language/filters) to mimic a Shopify store, but many of the tags and filters used in Shopify stores only make sense in the context of a specific web framework, so it is hard to generalise.

So, without spending a lot of time re-implementing all of Shopify's tags and filters, you are unlikely to be able to render a Shopify theme without some significant theme modifications.

Otherwise your code is broadly correct. I believe most (all?) `theme.liquid` layouts use `{{ content_for_header }}` and `{{ content_for_layout }}` variables, so the steps might look like this.

```python
from liquid import Environment
from liquid import FileExtensionLoader

# We use `Environment` instead of `Template` to support loading
# templates with `{% include %}` and `{% render %}`.
env = Environment(loader=FileExtensionLoader("/path/to/theme/"))

some_data = {
    "site": {"name", "MySite"},
    "collections": [
        {"title": "Some collection"},
    ]
}

# XXX: Expect errors here due to unexpected tags
theme_template = env.get_template("theme.liquid", globals=some_data)
content_template = env.get_template("some_page.liquid", globals=some_data)

content = content_template.render()
result = theme_template.render(content_for_layout=content)
```
